# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, I'm going to cover: 
* introduction to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercise to try for myself

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.10.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

2022-10-16 18:01:56.330092: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-16 18:01:56.330302: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330353: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330390: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330424: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

<tf.Tensor: shape=(), dtype=int32, numpy=7>

] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330487: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330523: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330557: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-10-16 18:01:56.330563: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are inst

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
vector.ndim

1

In [14]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[3, 16], [20, 19]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3, 16],
       [20, 19]], dtype=int32)>

In [15]:
matrix.ndim

2

In [18]:
# Create another matrix
matrix_2 = tf.constant([[10.,7.],
                        [3.,2.], 
                        [8.,9.]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
# What's the number dimensions of matrix_2
matrix_2.ndim
# number of dimensions are determined by how many elements are there in each vector

2

In [21]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [22]:
tensor.ndim

3

What we have create so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# tf.Variable

In [25]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [36]:
# Let's try changing one of the elementsi n our changeable tensor
# changeable_tensor[0] = 7
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [38]:
# Let's try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [39]:
# Let's try changing the unchangeable tensor
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

# Creating random Tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [45]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape =(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape =(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [49]:
# Shuffle a tensor (Valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim

2

In [50]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [68]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [60]:
# Shuffle our non-shuffled tensor

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed generation:
    https://www.tensorflow.org/api_docs/python/tf/random/set_seed
     and practice writing 5 random tensors and shuffle them.

In [69]:
tf_ex1 = tf.constant([[[1,2],
                       [3,4]],
                      [[5,6],
                       [7,8]],
                      [[9,10],
                       [11,12]]])

In [70]:
tf_ex1.ndim

3

In [89]:
tf.random.set_seed(42)
tf.random.shuffle(tf_ex1)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[ 1,  2],
        [ 3,  4]]], dtype=int32)>

In [93]:
tf_1 = tf.random.uniform(shape=[1,2], minval = -1., maxval = 0)
tf_1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.2597692 , -0.66061807]], dtype=float32)>